export const intentionExemples={
    intention1:{
        text: "Phasellus faucibus volutpat nisi. Donec eget tincidunt mauris. Donec elementum nisl id tellus pharetra, vehicula scelerisque orci volutpat. Aliquam eleifend, elit quis posuere placerat, odio nulla hendrerit diam, tristique efficitur velit velit ut felis. Etiam id finibus mi. ",
        causes: ["Alimentation", "Energie"],
        author: 'Alexandra Kisscool',
        image: 'windturbine.jpg',
        likes: "123",
        dislikes: "3",
        published: "1603984209753", 
    },
    intention2:{
        text: "Phasellus faucibus volutpat nisi. Donec eget tincidunt mauris. Donec elementum nisl id tellus pharetra, vehicula scelerisque orci volutpat. Aliquam eleifend, elit quis posuere placerat, odio nulla hendrerit diam, tristique efficitur velit velit ut felis. Etiam id finibus mi. ",
        causes: ["Alimentation", "Energie"],
        author: 'Alexandra Kisscool',
        image: 'vegetables.jpg',
        likes: "123",
        dislikes: "3",
        published: "1603984209753",
    },
    intention3:{
        text: "Phasellus faucibus volutpat nisi. Donec eget tincidunt mauris. Donec elementum nisl id tellus pharetra, vehicula scelerisque orci volutpat. Aliquam eleifend, elit quis posuere placerat, odio nulla hendrerit diam, tristique efficitur velit velit ut felis. Etiam id finibus mi. ",
        causes: ["Alimentation", "Energie"],
        author: 'Alexandra Kisscool',
        image: 'girl.png',
        likes: "123",
        dislikes: "3",
        published: "1603984209753",
    },
    intention4:{
        text: "Phasellus faucibus volutpat nisi. Donec eget tincidunt mauris. Donec elementum nisl id tellus pharetra, vehicula scelerisque orci volutpat. Aliquam eleifend, elit quis posuere placerat, odio nulla hendrerit diam, tristique efficitur velit velit ut felis. Etiam id finibus mi. ",
        causes: ["Alimentation", "Energie"],
        author: 'Alexandra Kisscool',
        image: 'auto.png',
        likes: "123",
        dislikes: "3",
        published: "1603984209753",
    },
    intention5:{
        text: "Phasellus faucibus volutpat nisi. Donec eget tincidunt mauris. Donec elementum nisl id tellus pharetra, vehicula scelerisque orci volutpat. Aliquam eleifend, elit quis posuere placerat, odio nulla hendrerit diam, tristique efficitur velit velit ut felis. Etiam id finibus mi. ",
        causes: ["Alimentation", "Energie"],
        author: 'Alexandra Kisscool',
        image: 'clothes.png',
        likes: "123",
        dislikes: "3",
        published: "1603984209753",
    },
}